### ISSUE TITLE
Another question about vocab_size

### ISSUE THREAD

**Issue by liushui9404** [tchayintr/thbert#2]
Thank you for solving the previous problem.
I haved downloaded the latest files. However, _vocab_size_ in bert_config.json is 128000, but there are 128004 words in vocab.txt. Is there any problem here？I think _vocab_size_ and the number of words in the vocab.txt should be the same.

**Comment by tchayintr** [comment]
I originally built the model from scratch with the original vocabulary size of 128K. After the model has been trained, the output vocabulary (vocab.txt) with additional tokens (e.g. [PAD], [SEP], [CLS]) are automatically pushed. 

> the vocabulary size in my bert_config.json is set to 128000 but there are 128004 words in vocab.txt. Is there any problem here?

Yes, it will discard four tokens referring the vocab.txt file and might slightly affect the overall performance.
You can just simply alter the vocabulary size to 128004 or so in the configuration file (bert_config.json) whenever you want to reproduce and make use of the model somehow.

Again, I would like to thank you for looking into the detail. I will update the configuration file on the cloud.
Sorry for wasting your time because of my mistake.
